// <auto-generated />
using System;
using AutoAlert.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoAlert.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoAlert.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SettingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SettingsId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AutoAlert.Data.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EngineOilReminderId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EuroType")
                        .HasColumnType("int");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<Guid?>("InshurenceReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TaxPayed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TechnicalCheckExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransmissionOilReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VignetteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearOfMake")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineOilReminderId")
                        .IsUnique();

                    b.HasIndex("InshurenceReminderId")
                        .IsUnique()
                        .HasFilter("[InshurenceReminderId] IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TransmissionOilReminderId")
                        .IsUnique()
                        .HasFilter("[TransmissionOilReminderId] IS NOT NULL");

                    b.HasIndex("VignetteId")
                        .IsUnique()
                        .HasFilter("[VignetteId] IS NOT NULL");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.EngineOilReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<int>("MileageOfLastChange")
                        .HasColumnType("int");

                    b.Property<int>("MileageOfNextChange")
                        .HasColumnType("int");

                    b.Property<string>("OilType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("EngineOilReminders");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.InsurenceReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("InsurenceReminders");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3295e68f-519c-4110-947d-10020365b95c"),
                            Name = "Sliven"
                        },
                        new
                        {
                            Id = new Guid("2219d8e0-579c-4110-945d-10120365b95c"),
                            Name = "Ruse"
                        },
                        new
                        {
                            Id = new Guid("3195e68b-519c-4110-946d-10120365b95c"),
                            Name = "Smolyan"
                        },
                        new
                        {
                            Id = new Guid("1c19d8f0-57ac-4110-944d-10220365b95c"),
                            Name = "Pernik"
                        },
                        new
                        {
                            Id = new Guid("2d19d8e2-57bc-4110-943d-10320365b95c"),
                            Name = "Targovishte"
                        },
                        new
                        {
                            Id = new Guid("22cb1119-9934-4230-b0a0-1faf04b6f95c"),
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = new Guid("01faf0e4-174f-4750-807d-22f60e3a1a5c"),
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = new Guid("11faf812-1791-4750-808d-22f60e3a1a5c"),
                            Name = "Kardzhali"
                        },
                        new
                        {
                            Id = new Guid("14faf3c8-1791-4750-808d-22f60e3a1a5c"),
                            Name = "Varna"
                        },
                        new
                        {
                            Id = new Guid("12faf5c0-1791-4750-809d-22f60e3a1a5c"),
                            Name = "Stara Zagora"
                        },
                        new
                        {
                            Id = new Guid("02b3d7c8-57ad-4038-bc66-4293e254b56c"),
                            Name = "Haskovo"
                        },
                        new
                        {
                            Id = new Guid("05fafe08-1c4f-42a0-aa6d-52b8faf7aa5c"),
                            Name = "Pazardzhik"
                        },
                        new
                        {
                            Id = new Guid("10faf664-238f-4100-9531-55b8faf3895c"),
                            Name = "Pleven"
                        },
                        new
                        {
                            Id = new Guid("00faf4b0-5c38-4720-98e3-714805b16a5c"),
                            Name = "Kyustendil"
                        },
                        new
                        {
                            Id = new Guid("23d1a252-593c-4b50-9141-77faf6604a5c"),
                            Name = "Razgrad"
                        },
                        new
                        {
                            Id = new Guid("03d1a262-594c-4b50-9151-78faf6604a5c"),
                            Name = "Montana"
                        },
                        new
                        {
                            Id = new Guid("26d1a242-594c-4b50-9131-79faf6604a5c"),
                            Name = "Silistra"
                        },
                        new
                        {
                            Id = new Guid("4e27b2d5-7954-4610-b8fd-8143614c778d"),
                            Name = "Blagoevgrad"
                        },
                        new
                        {
                            Id = new Guid("04059520-78d2-4456-9364-90e1d1d3465c"),
                            Name = "Gabrovo"
                        },
                        new
                        {
                            Id = new Guid("2456e699-5173-4094-a749-91614e160a5c"),
                            Name = "Lovech"
                        },
                        new
                        {
                            Id = new Guid("3395e693-5193-4084-a769-91714e160a5c"),
                            Name = "Shumen"
                        },
                        new
                        {
                            Id = new Guid("3495e697-5193-4084-a779-91714e160a5c"),
                            Name = "Plovdiv"
                        },
                        new
                        {
                            Id = new Guid("0afaf1f8-1a8f-40e0-b191-d605faf126cb"),
                            Name = "Sofia-Grad"
                        },
                        new
                        {
                            Id = new Guid("0858a1f7-1a09-40e0-b1b1-d605faf126cb"),
                            Name = "Dobrich"
                        },
                        new
                        {
                            Id = new Guid("cf3f3ba8-6459-41c5-8bf5-49992f623c77"),
                            Name = "Veliko Tarnovo"
                        });
                });

            modelBuilder.Entity("AutoAlert.Data.Models.TransmitionOilReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<int>("MileageOfLastChange")
                        .HasColumnType("int");

                    b.Property<int>("MileageOfNextChange")
                        .HasColumnType("int");

                    b.Property<string>("OilType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("TransmitionOilReminders");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EmailReminders")
                        .HasColumnType("bit");

                    b.Property<bool>("GlobalReminders")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.VignetteReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateBought")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VignetteReminders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoAlert.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("AutoAlert.Data.Models.UserSettings", "Settings")
                        .WithOne("User")
                        .HasForeignKey("AutoAlert.Data.Models.ApplicationUser", "SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.Car", b =>
                {
                    b.HasOne("AutoAlert.Data.Models.EngineOilReminder", "EngineOilReminder")
                        .WithOne("Car")
                        .HasForeignKey("AutoAlert.Data.Models.Car", "EngineOilReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoAlert.Data.Models.InsurenceReminder", "InsurenceReminder")
                        .WithOne("Car")
                        .HasForeignKey("AutoAlert.Data.Models.Car", "InshurenceReminderId");

                    b.HasOne("AutoAlert.Data.Models.ApplicationUser", "User")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoAlert.Data.Models.Region", "Region")
                        .WithMany("Cars")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoAlert.Data.Models.TransmitionOilReminder", "TransmitionOilReminder")
                        .WithOne("Car")
                        .HasForeignKey("AutoAlert.Data.Models.Car", "TransmissionOilReminderId");

                    b.HasOne("AutoAlert.Data.Models.VignetteReminder", "VignetteReminder")
                        .WithOne("Car")
                        .HasForeignKey("AutoAlert.Data.Models.Car", "VignetteId");

                    b.Navigation("EngineOilReminder");

                    b.Navigation("InsurenceReminder");

                    b.Navigation("Region");

                    b.Navigation("TransmitionOilReminder");

                    b.Navigation("User");

                    b.Navigation("VignetteReminder");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.Notification", b =>
                {
                    b.HasOne("AutoAlert.Data.Models.Car", "Car")
                        .WithMany("Notifications")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoAlert.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoAlert.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoAlert.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoAlert.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoAlert.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoAlert.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.Car", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.EngineOilReminder", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoAlert.Data.Models.InsurenceReminder", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoAlert.Data.Models.Region", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoAlert.Data.Models.TransmitionOilReminder", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoAlert.Data.Models.UserSettings", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoAlert.Data.Models.VignetteReminder", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
